In [2]:
!pip install snowflake-snowpark-python

Collecting snowflake-snowpark-python
  Downloading snowflake_snowpark_python-1.54.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: setuptools>=40.6.0 in /opt/conda/lib/python3.12/site-packages (from snowflake-snowpark-python) (75.8.0)
Requirement already satisfied: wheel in /opt/conda/lib/python3.12/site-packages (from snowflake-snowpark-python) (0.45.1)
Requirement already satisfied: snowflake-connector-python<5.0.0,>=3.17.0 in /opt/conda/lib/python3.12/site-packages (from snowflake-snowpark-python) (3.18.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.1.0 in /opt/conda/lib/python3.12/site-packages (from snowflake-snowpark-python) (4.16.0)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.12/site-packages (from snowflake-snowpark-python) (6.0.2)
Requirement already satisfied: cloudpickle!=2.1.0,!=2.2.0,<=3.1.1,>=1.6.0 in /opt/conda/lib/python3.12/site-packages (from snowflake-snowpark-python) (3.1.1)
Requirement already satisfied: protobuf<6.34,>=3.20 in /opt/conda/lib/python3.12/site-packages (from snowflake-snowpark-python) (6.33.6)
Requirement already satisfied: python-dateutil in /opt/conda/lib/python3.12/site-packages (from snowflake-snowpark-python) (2.9.0.post0)
Requirement already satisfied: tzlocal in /opt/conda/lib/python3.12/site-packages (from snowflake-snowpark-python) (5.2)
Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in /opt/conda/lib/python3.12/site-packages (from snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (1.5.1)
Requirement already satisfied: boto3>=1.24 in /opt/conda/lib/python3.12/site-packages (from snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (1.43.74)
Requirement already satisfied: botocore>=1.24 in /opt/conda/lib/python3.12/site-packages (from snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (1.43.74)
Requirement already satisfied: cffi<2.0.0,>=1.9 in /opt/conda/lib/python3.12/site-packages (from snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (1.17.1)
Requirement already satisfied: cryptography>=3.1.0 in /opt/conda/lib/python3.12/site-packages (from snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (46.0.0)
Requirement already satisfied: pyOpenSSL<26.0.0,>=22.0.0 in /opt/conda/lib/python3.12/site-packages (from snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (25.3.0)
Requirement already satisfied: pyjwt<3.0.0 in /opt/conda/lib/python3.12/site-packages (from snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (2.10.1)
Requirement already satisfied: pytz in /opt/conda/lib/python3.12/site-packages (from snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (2024.1)
Requirement already satisfied: requests<3.0.0 in /opt/conda/lib/python3.12/site-packages (from snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (2.34.2)
Requirement already satisfied: packaging in /opt/conda/lib/python3.12/site-packages (from snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (24.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.12/site-packages (from snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (2024.12.14)
Requirement already satisfied: filelock<4,>=3.5 in /opt/conda/lib/python3.12/site-packages (from snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (3.32.3)
Requirement already satisfied: sortedcontainers>=2.4.0 in /opt/conda/lib/python3.12/site-packages (from snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (2.4.0)
Requirement already satisfied: platformdirs<5.0.0,>=2.6.0 in /opt/conda/lib/python3.12/site-packages (from snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (4.3.6)
Requirement already satisfied: tomlkit in /opt/conda/lib/python3.12/site-packages (from snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (0.15.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil->snowflake-snowpark-python) (1.17.0)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from boto3>=1.24->snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (1.1.0)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in /opt/conda/lib/python3.12/site-packages (from boto3>=1.24->snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (0.19.2)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /opt/conda/lib/python3.12/site-packages (from botocore>=1.24->snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (2.3.0)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.12/site-packages (from cffi<2.0.0,>=1.9->snowflake-connector-python<5.0.0,>=3.17.0->snowflake-snowpark-python) (2.22)
Downloading snowflake_snowpark_python-1.54.0-py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 57.0 MB/s eta 0:00:00
Installing collected packages: snowflake-snowpark-python
Successfully installed snowflake-snowpark-python-1.54.0

In [3]:
import pandas as pd
import numpy as np
import os
import sklearn
import sys
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
import builtins

In [5]:
from snowflake.snowpark import Session
from snowflake.snowpark.functions import collect_set, stddev, row_number, size, col, min as s_min, max as s_max, abs as s_abs, avg, median, month, year, when, round, is_null, upper, trim, regexp_replace, split, sum, datediff, dateadd, to_timestamp, to_date, last_day, current_date, least, lag, lit, coalesce, greatest, count_distinct, count, expr, try_cast, array_slice, array_contains, array_construct, array_compact, sort_array, concat_ws, concat, to_char, date_trunc
from snowflake.snowpark.window import Window

# Functions to read in Snowflake data

In [6]:
import snowflake.snowpark
print(snowflake.snowpark.__version__)

1.54.0

In [7]:
def create_snowpark_session():
    # Create session with connection parameters
    connection_parameters = {
        "account": "phrwdstore.us-east-1",
        "user": "vishnu.suresh1.ext@bayer.com", #add your email here
        "role": "RWDSTORE_TRINETX_EHR_ATTRCM_R",  # Primary role of the database
        "warehouse": "COMPUTE_WH",
        "database": "TRINETX_EHR_ATTRCM",
        #"schema": "EDCOY",
        "authenticator":"externalbrowser"
    }
    
    session = Session.builder.configs(connection_parameters).create()
    return session

In [ ]:
session = create_snowpark_session()

# ATTR-CM

## Step 1

In [32]:
tafamidis_codes = list(pd.read_excel("Aco_Vutri_TriNetX_Feas._codelists_JUL2026.xlsx", sheet_name = "Tafamidis")["Concept Code"])

In [33]:
tafamidis_codes = [str(code) for code in tafamidis_codes]

In [34]:
# STEP 1: Get first tafamidis code on/after 2019-06-01
step1_taf_df = (
    session.table("DATA_202511.MEDICATION")
    .filter(col("CODE_SYSTEM") == "RxNorm")
    .filter(col("CODE").isin(tafamidis_codes))
    .filter(col("START_DATE") >= "2019-06-01")
    .filter(col("START_DATE").is_not_null())
    .group_by("PATIENT_ID")
    .agg(s_min("START_DATE").alias("INDEX_DATE"))
)
print(f"Step 1: {step1_taf_df.count()} patients with tafamidis >= 2019-06-01")

Step 1: 9270 patients with tafamidis >= 2019-06-01

In [35]:
session.table("DATA_202511.MEDICATION").filter(col("CODE_SYSTEM") == "RxNorm").filter(col("CODE").isin(tafamidis_codes)).filter(col("START_DATE") >= "2019-06-01").filter(col("START_DATE").is_not_null()).select('CODE').distinct().show()

-----------
|"CODE"   |
-----------
|1545063  |
-----------

## Step 2

In [36]:
# STEP 2: Of Step 1, exclude those with tafamidis BEFORE INDEX_DATE
prior_tafs = (
    step1_taf_df
    .join(
        session.table("DATA_202511.MEDICATION")
        .filter(col("CODE_SYSTEM") == "RxNorm")
        .filter(col("CODE").isin(tafamidis_codes)),
        on="PATIENT_ID"
    )
    .filter(col("START_DATE") < col("INDEX_DATE"))
    .select("PATIENT_ID").distinct()
)

step2_taf_df = step1_taf_df.join(prior_tafs, on="PATIENT_ID", how="anti")
print(f"Step 2: {step2_taf_df.count()} patients after excluding prior tafamidis")

Step 2: 9226 patients after excluding prior tafamidis

## Step 3

In [37]:
eplontersen_codes = list(pd.read_excel("Aco_Vutri_TriNetX_Feas._codelists_JUL2026.xlsx", sheet_name = "Eplontersen")["Concept Code"])
eplontersen_codes = [str(code) for code in eplontersen_codes ]

In [38]:
inotersen_codes = list(pd.read_excel("Aco_Vutri_TriNetX_Feas._codelists_JUL2026.xlsx", sheet_name = "Inotersen")["Concept Code"])
inotersen_codes = [str(code) for code in inotersen_codes]

In [39]:
patisiran_codes = list(pd.read_excel("Aco_Vutri_TriNetX_Feas._codelists_JUL2026.xlsx", sheet_name = "Patisiran")["Concept Code"])
patisiran_codes = [str(code) for code in patisiran_codes]

In [40]:
other_drugs = eplontersen_codes + inotersen_codes + patisiran_codes

In [41]:
exclusions = (
    step2_taf_df
    .join(
        session.table("DATA_202511.MEDICATION")
        .filter(col("CODE_SYSTEM") == "RxNorm")
        .filter(col("CODE").isin(other_drugs)),
        on="PATIENT_ID"
    )
    .filter(col("START_DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID").distinct()
)

step3_taf_df = step2_taf_df.join(exclusions, on="PATIENT_ID", how="anti")
print(f"Step 3: {step3_taf_df.count()} after Step 3")

Step 3: 9139 after Step 3

## Step 4

In [42]:
# ICD-10-CM codes
icd10_codes = [
    "I50", "I50.1", "I50.2", "I50.20", "I50.21", "I50.22", "I50.23",
    "I50.3", "I50.30", "I50.31", "I50.32", "I50.33",
    "I50.4", "I50.40", "I50.41", "I50.42", "I50.43",
    "I50.8", "I50.81", "I50.810", "I50.811", "I50.812", "I50.813", "I50.814",
    "I50.82", "I50.83", "I50.84", "I50.89", "I50.9",
    "I11.0", "I13.0", "I13.2",
]

# ICD-9-CM codes
icd9_codes = [
    "428", "428.0", "428.1", "428.2", "428.20", "428.21", "428.22", "428.23",
    "428.3", "428.30", "428.31", "428.32", "428.33",
    "428.4", "428.40", "428.41", "428.42", "428.43",
    "428.9",
    "402.01", "402.11", "402.91",
    "404.01", "404.03", "404.11", "404.13", "404.91", "404.93",
]

In [43]:
# Build lookup table: Code | Code_System
icd10_df = pd.DataFrame({"Code": icd10_codes, "Code_System": "ICD-10-CM"})
icd9_df = pd.DataFrame({"Code": icd9_codes, "Code_System": "ICD-9-CM"})

hf_codes_lookup = pd.concat([icd10_df, icd9_df], ignore_index=True)

# Extract code lists by system for use in Snowpark filtering
hf_codes_icd10 = hf_codes_lookup[hf_codes_lookup["Code_System"] == "ICD-10-CM"]["Code"].tolist()
hf_codes_icd9  = hf_codes_lookup[hf_codes_lookup["Code_System"] == "ICD-9-CM"]["Code"].tolist()

In [44]:
# --- Code lists ---
# Amyloidosis codes (note: differs slightly between step 4 and 4a)
amyloidosis_codes_step4  = ["E85", "E85.0", "E85.2", "E85.4", "E85.82", "E85.89", "E85.9"]
#amyloidosis_codes_step4a = ["E85", "E85.0", "E85.2", "E85.4", "E85.82", "E85.9"]  # no E85.89?

In [45]:
# Cardiomyopathy/HF codes = your HF_codes list (from Excel) + these extra I-codes
extra_cm_codes = ["I42.2", "I42.5", "I42.8", "I42.9", "I43"]

In [46]:
cm_codes_icd10 = hf_codes_icd10 + extra_cm_codes   
cm_codes_icd9  = hf_codes_icd9

In [47]:
# --- Pull diagnosis records prior to/on index ---

def get_amyloidosis_records(codes):
    return (
        step3_taf_df
        .join(
            session.table("DATA_202511.DIAGNOSIS")
            .filter(col("CODE").isin(codes))
            .filter(col("DATE").is_not_null()),
            on="PATIENT_ID"
        )
        .filter(col("DATE") <= col("INDEX_DATE"))
        .select("PATIENT_ID", col("CODE").alias("E85_CODE"), col("DATE").alias("E85_DATE"))
    )

In [48]:
def get_cm_records():
    return (
        step3_taf_df
        .join(
            session.table("DATA_202511.DIAGNOSIS")
            .filter(
                (col("CODE_SYSTEM") == "ICD-10-CM") & col("CODE").isin(cm_codes_icd10)
                | (col("CODE_SYSTEM") == "ICD-9-CM") & col("CODE").isin(cm_codes_icd9)
            )
            .filter(col("DATE").is_not_null()),
            on="PATIENT_ID"
        )
        .filter(col("DATE") <= col("INDEX_DATE"))
        .select("PATIENT_ID", col("CODE").alias("CM_CODE"), col("CODE_SYSTEM").alias("CM_CODE_SYSTEM"), col("DATE").alias("CM_DATE"))
    )

In [49]:
cm_records = get_cm_records() #same for 4 and 4a

In [50]:
# ============ STEP 4: any time apart ============
e85_records_4 = get_amyloidosis_records(amyloidosis_codes_step4)

step4_taf_df = e85_records_4.join(cm_records, on="PATIENT_ID", how="inner")

print(f"Step 4: {step4_taf_df.select('PATIENT_ID').distinct().count()} patients")
print("\nBreakdown by E85 code + CM code:")
step4_taf_df.group_by("E85_CODE", "CM_CODE", "CM_CODE_SYSTEM").count().order_by(col("COUNT").desc()).show(30)

Step 4: 6391 patients

Breakdown by E85 code + CM code:
-------------------------------------------------------
|"E85_CODE"  |"CM_CODE"  |"CM_CODE_SYSTEM"  |"COUNT"  |
-------------------------------------------------------
|E85.4       |I43        |ICD-10-CM         |1051211  |
|E85.4       |I50.9      |ICD-10-CM         |543290   |
|E85.4       |I50.32     |ICD-10-CM         |429544   |
|E85.4       |I50.22     |ICD-10-CM         |306060   |
|E85.4       |I50.30     |ICD-10-CM         |205961   |
|E85.4       |I50.33     |ICD-10-CM         |204777   |
|E85.4       |I11.0      |ICD-10-CM         |194122   |
|E85.4       |I13.0      |ICD-10-CM         |177295   |
|E85.4       |I42.9      |ICD-10-CM         |171866   |
|E85.4       |I50.23     |ICD-10-CM         |166920   |
|E85.9       |I43        |ICD-10-CM         |163041   |
|E85.4       |I50.20     |ICD-10-CM         |145979   |
|E85.4       |I50.42     |ICD-10-CM         |140934   |
|E85.9       |I50.9      |ICD-10-CM         |136588   |
|E85.4       |I42.8      |ICD-10-CM         |135585   |
|E85.4       |I50.40     |ICD-10-CM         |124470   |
|E85.82      |I43        |ICD-10-CM         |116953   |
|E85.9       |I50.32     |ICD-10-CM         |105265   |
|E85.4       |I50.43     |ICD-10-CM         |97258    |
|E85.82      |I50.32     |ICD-10-CM         |94328    |
|E85.4       |I50.21     |ICD-10-CM         |78125    |
|E85.82      |I50.9      |ICD-10-CM         |75903    |
|E85.9       |I50.22     |ICD-10-CM         |67206    |
|E85.4       |I42.5      |ICD-10-CM         |61118    |
|E85.82      |I50.22     |ICD-10-CM         |57873    |
|E85.9       |I50.30     |ICD-10-CM         |52032    |
|E85.82      |I11.0      |ICD-10-CM         |46046    |
|E85.9       |I11.0      |ICD-10-CM         |45513    |
|E85.89      |I50.32     |ICD-10-CM         |43557    |
|E85.9       |I13.0      |ICD-10-CM         |42297    |
-------------------------------------------------------

In [51]:
print("Step 4 — Most common E85 codes:")
step4_taf_df.select("PATIENT_ID", "E85_CODE").distinct() \
    .group_by("E85_CODE").count() \
    .order_by(col("COUNT").desc()).show(20)

Step 4 — Most common E85 codes:
------------------------
|"E85_CODE"  |"COUNT"  |
------------------------
|E85.4       |5539     |
|E85.9       |2608     |
|E85.82      |2129     |
|E85.89      |785      |
|E85.2       |248      |
|E85.0       |64       |
|E85         |3        |
------------------------

In [52]:
print("Step 4 — Most common CM codes:")
step4_taf_df.select("PATIENT_ID", "CM_CODE", "CM_CODE_SYSTEM").distinct() \
    .group_by("CM_CODE", "CM_CODE_SYSTEM").count() \
    .order_by(col("COUNT").desc()).show(30)

Step 4 — Most common CM codes:
------------------------------------------
|"CM_CODE"  |"CM_CODE_SYSTEM"  |"COUNT"  |
------------------------------------------
|I43        |ICD-10-CM         |5258     |
|I50.9      |ICD-10-CM         |3380     |
|I50.32     |ICD-10-CM         |2512     |
|I11.0      |ICD-10-CM         |2366     |
|I42.9      |ICD-10-CM         |2108     |
|I50.22     |ICD-10-CM         |1780     |
|I50.30     |ICD-10-CM         |1573     |
|I42.8      |ICD-10-CM         |1539     |
|I13.0      |ICD-10-CM         |1539     |
|I50.33     |ICD-10-CM         |1454     |
|I50.20     |ICD-10-CM         |1307     |
|I50.23     |ICD-10-CM         |1113     |
|I50.42     |ICD-10-CM         |990      |
|I50.43     |ICD-10-CM         |906      |
|I50.21     |ICD-10-CM         |671      |
|I50.31     |ICD-10-CM         |652      |
|I42.5      |ICD-10-CM         |632      |
|I42.2      |ICD-10-CM         |425      |
|428.0      |ICD-9-CM          |338      |
|I50.41     |ICD-10-CM         |273      |
|I50.1      |ICD-10-CM         |246      |
|I50.82     |ICD-10-CM         |224      |
|I50.40     |ICD-10-CM         |194      |
|428.32     |ICD-9-CM          |176      |
|428.9      |ICD-9-CM          |159      |
|428.22     |ICD-9-CM          |157      |
|I50.810    |ICD-10-CM         |131      |
|428.42     |ICD-9-CM          |125      |
|I50.84     |ICD-10-CM         |106      |
|I50.89     |ICD-10-CM         |91       |
------------------------------------------

### Amyloidosis analysis

In [53]:
# Population: patients meeting Step 4 (swap for step4a_df as needed)
population_ids = step4_taf_df.select("PATIENT_ID").distinct()
total_n = population_ids.count()
print(f"Total patients in population: {total_n}")

# Distinct (PATIENT_ID, E85_CODE) pairs for this population
patient_e85_codes = (
    e85_records_4
    .join(population_ids, on="PATIENT_ID", how="inner")
    .select("PATIENT_ID", "E85_CODE")
    .distinct()
)

# How many distinct amyloidosis codes does each patient have?
patient_code_counts = (
    patient_e85_codes
    .group_by("PATIENT_ID")
    .agg(count_distinct("E85_CODE").alias("N_DISTINCT_CODES"))
)

Total patients in population: 6391

In [54]:
# ---- TABLE 1: ≥1 code (any) ----
table_any = (
    patient_e85_codes
    .group_by("E85_CODE")
    .agg(count_distinct("PATIENT_ID").alias("N_ANY"))
    .order_by(col("N_ANY").desc())
)
print("Table 1: >=1 code (any)")
table_any.show(20)

Table 1: >=1 code (any)
------------------------
|"E85_CODE"  |"N_ANY"  |
------------------------
|E85.4       |5539     |
|E85.9       |2608     |
|E85.82      |2129     |
|E85.89      |785      |
|E85.2       |248      |
|E85.0       |64       |
|E85         |3        |
------------------------

In [55]:
# ---- TABLE 2: only this code (patient has exactly 1 distinct code, and it's this one) ----
only_code_patients = (
    patient_e85_codes
    .join(patient_code_counts, on="PATIENT_ID", how="inner")
    .filter(col("N_DISTINCT_CODES") == 1)
)

table_only = (
    only_code_patients
    .group_by("E85_CODE")
    .agg(count_distinct("PATIENT_ID").alias("N_ONLY"))
    .order_by(col("N_ONLY").desc())
)
print("Table 2: only this code")
table_only.show(20)

Table 2: only this code
-------------------------
|"E85_CODE"  |"N_ONLY"  |
-------------------------
|E85.4       |2389      |
|E85.82      |282       |
|E85.9       |265       |
|E85.89      |64        |
|E85.2       |7         |
|E85.0       |5         |
-------------------------

### Cardiomyopathy analysis

In [56]:
# Distinct (PATIENT_ID, CM_CODE) pairs for this population
# Using cm_records (already filtered to DATE <= INDEX_DATE)
patient_cm_codes = (
    cm_records
    .join(population_ids, on="PATIENT_ID", how="inner")
    .select("PATIENT_ID", "CM_CODE")
    .distinct()
)

# How many distinct CM codes does each patient have (out of the full CM list)?
patient_cm_code_counts = (
    patient_cm_codes
    .group_by("PATIENT_ID")
    .agg(count_distinct("CM_CODE").alias("N_DISTINCT_CM_CODES"))
)

In [57]:
# ---- TABLE 1: >=1 code (any), restricted to the I42/I43 cardiomyopathy codes ----
cm_codes_of_interest = ["I42.2", "I42.5", "I42.8", "I42.9", "I43"]

table_cm_any = (
    patient_cm_codes
    .filter(col("CM_CODE").isin(cm_codes_of_interest))
    .group_by("CM_CODE")
    .agg(count_distinct("PATIENT_ID").alias("N_ANY"))
    .order_by(col("N_ANY").desc())
)
print("Table 1: >=1 cardiomyopathy code (any)")
table_cm_any.show(20)

Table 1: >=1 cardiomyopathy code (any)
-----------------------
|"CM_CODE"  |"N_ANY"  |
-----------------------
|I43        |5258     |
|I42.9      |2108     |
|I42.8      |1539     |
|I42.5      |632      |
|I42.2      |425      |
-----------------------

In [58]:
# ---- TABLE 2: only this code (patient's ONLY CM code overall is this one) ----
only_cm_code_patients = (
    patient_cm_codes
    .join(patient_cm_code_counts, on="PATIENT_ID", how="inner")
    .filter(col("N_DISTINCT_CM_CODES") == 1)
)

table_cm_only = (
    only_cm_code_patients
    .filter(col("CM_CODE").isin(cm_codes_of_interest))
    .group_by("CM_CODE")
    .agg(count_distinct("PATIENT_ID").alias("N_ONLY"))
    .order_by(col("N_ONLY").desc())
)
print("Table 2: only this cardiomyopathy code")
table_cm_only.show(20)

Table 2: only this cardiomyopathy code
------------------------
|"CM_CODE"  |"N_ONLY"  |
------------------------
|I43        |646       |
|I42.9      |45        |
|I42.8      |18        |
|I42.5      |11        |
|I42.2      |10        |
------------------------

#### Additional check for E85.8

In [59]:
population_df = step3_taf_df.select("PATIENT_ID", "INDEX_DATE")

In [60]:
diagnosis_tbl = session.table("DATA_202511.DIAGNOSIS")

In [61]:
# ==================================================
# Get ALL amyloidosis (E85.x) codes present for step 3 patients, <= index date
# Use a broad E85 wildcard search, not just your predefined code list,
# so we catch E85.8 even if it wasn't in your original lists
# ==================================================
all_e85_records = (
    diagnosis_tbl
    .filter(col("CODE").like("E85%"))
    .filter(col("DATE").is_not_null())
    .join(population_df, on="PATIENT_ID", how="inner")
    .filter(col("DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID", col("CODE").alias("E85_CODE"))
    .distinct()
)

In [62]:
# Confirm E85.8 exists in the data
e85_8_check = all_e85_records.filter(col("E85_CODE") == "E85.8")
print(f"Patients with E85.8 at all: {e85_8_check.select('PATIENT_ID').distinct().count()}")

Patients with E85.8 at all: 39

In [63]:
# How many distinct amyloidosis codes does each patient have (using full E85.x set)?
patient_e85_code_counts = (
    all_e85_records
    .group_by("PATIENT_ID")
    .agg(count_distinct("E85_CODE").alias("N_DISTINCT_CODES"))
)

In [64]:
# Patients for whom E85.8 is their ONLY amyloidosis code
e85_8_only_patients = (
    all_e85_records
    .filter(col("E85_CODE") == "E85.8")
    .join(patient_e85_code_counts, on="PATIENT_ID", how="inner")
    .filter(col("N_DISTINCT_CODES") == 1)
    .select("PATIENT_ID")
    .distinct()
)

In [65]:
n_e85_8_only = e85_8_only_patients.count()
print(f"Patients with E85.8 as their ONLY amyloidosis code: {n_e85_8_only}")

Patients with E85.8 as their ONLY amyloidosis code: 0

## Step 4a

In [66]:
# ============ STEP 4a: within 2 years ============
e85_records_4a = get_amyloidosis_records(amyloidosis_codes_step4)

step4a_pairs = e85_records_4a.join(cm_records, on="PATIENT_ID", how="inner")

step4a_taf_df = step4a_pairs.filter(
    s_abs(datediff("YEAR", col("E85_DATE"), col("CM_DATE"))) <= 2
)

In [67]:
print(f"\nStep 4a: {step4a_taf_df.select('PATIENT_ID').distinct().count()} patients")
print("\nBreakdown by E85 code + CM code (within 2 years):")
step4a_taf_df.group_by("E85_CODE", "CM_CODE", "CM_CODE_SYSTEM").count().order_by(col("COUNT").desc()).show(30)

Step 4a: 6380 patients

Breakdown by E85 code + CM code (within 2 years):
-------------------------------------------------------
|"E85_CODE"  |"CM_CODE"  |"CM_CODE_SYSTEM"  |"COUNT"  |
-------------------------------------------------------
|E85.4       |I43        |ICD-10-CM         |983233   |
|E85.4       |I50.9      |ICD-10-CM         |423744   |
|E85.4       |I50.32     |ICD-10-CM         |368779   |
|E85.4       |I50.22     |ICD-10-CM         |261118   |
|E85.4       |I50.33     |ICD-10-CM         |182795   |
|E85.4       |I50.30     |ICD-10-CM         |180130   |
|E85.4       |I11.0      |ICD-10-CM         |167989   |
|E85.4       |I13.0      |ICD-10-CM         |159581   |
|E85.9       |I43        |ICD-10-CM         |144643   |
|E85.4       |I50.23     |ICD-10-CM         |140910   |
|E85.4       |I50.20     |ICD-10-CM         |132340   |
|E85.4       |I42.9      |ICD-10-CM         |131955   |
|E85.4       |I50.42     |ICD-10-CM         |123466   |
|E85.4       |I50.40     |ICD-10-CM         |119995   |
|E85.4       |I42.8      |ICD-10-CM         |117985   |
|E85.9       |I50.9      |ICD-10-CM         |115736   |
|E85.82      |I43        |ICD-10-CM         |105781   |
|E85.9       |I50.32     |ICD-10-CM         |88719    |
|E85.4       |I50.43     |ICD-10-CM         |84897    |
|E85.82      |I50.32     |ICD-10-CM         |81422    |
|E85.4       |I50.21     |ICD-10-CM         |61391    |
|E85.82      |I50.9      |ICD-10-CM         |58712    |
|E85.9       |I50.22     |ICD-10-CM         |57335    |
|E85.4       |I42.5      |ICD-10-CM         |55414    |
|E85.82      |I50.22     |ICD-10-CM         |48704    |
|E85.9       |I50.30     |ICD-10-CM         |43513    |
|E85.82      |I11.0      |ICD-10-CM         |41805    |
|E85.9       |I11.0      |ICD-10-CM         |39206    |
|E85.9       |I13.0      |ICD-10-CM         |36160    |
|E85.89      |I50.32     |ICD-10-CM         |35340    |
-------------------------------------------------------

# hATTR-PN

## Step 1

In [68]:
vutrisiran_codes = list(pd.read_excel("Aco_Vutri_TriNetX_Feas._codelists_JUL2026.xlsx", sheet_name = "Vutrisiran")["Concept Code"])
vutrisiran_codes = [str(code) for code in vutrisiran_codes]

In [69]:
# STEP 1: First vutrisiran code BEFORE 2025-03-01
step1_vut_df = (
    session.table("DATA_202511.MEDICATION")
    .filter(col("CODE_SYSTEM") == "RxNorm")
    .filter(col("CODE").isin(vutrisiran_codes))
    .filter(col("START_DATE") < "2025-03-01")
    .filter(col("START_DATE").is_not_null())
    .group_by("PATIENT_ID")
    .agg(s_min("START_DATE").alias("INDEX_DATE"))
)
print(f"Step 1: {step1_vut_df.count()} patients")

Step 1: 413 patients

In [70]:
session.table("DATA_202511.MEDICATION").filter(col("CODE_SYSTEM") == "RxNorm").filter(col("CODE").isin(vutrisiran_codes)).filter(col("START_DATE") >= "2019-06-01").filter(col("START_DATE").is_not_null()).select('CODE').distinct().show()

-----------
|"CODE"   |
-----------
|2604578  |
-----------

## Step 2

In [71]:
# STEP 2: Exclude patients with vutrisiran BEFORE their index date
prior_vutrisiran = (
    step1_vut_df
    .join(
        session.table("DATA_202511.MEDICATION")
        .filter(col("CODE_SYSTEM") == "RxNorm")
        .filter(col("CODE").isin(vutrisiran_codes)),
        on="PATIENT_ID"
    )
    .filter(col("START_DATE") < col("INDEX_DATE"))
    .select("PATIENT_ID").distinct()
)

step2_vut_df = step1_vut_df.join(prior_vutrisiran, on="PATIENT_ID", how="anti")
print(f"Step 2: {step2_vut_df.count()} patients after excluding prior vutrisiran")

Step 2: 413 patients after excluding prior vutrisiran

## Step 3

In [72]:
e85_1_code = ["E85.1"]
e85_group_codes = ["E85", "E85.2", "E85.89", "E85.9"]
neuro_codes = [
    "G60", "G60.3", "G60.9",
    "G61", "G61.8", "G61.82", "G61.89", "G61.9",
    "G62", "G62.8", "G62.89", "G62.9",
    "G63", "G64"
]

In [73]:
# ---- E85.1 records (standalone qualifier) ----
e85_1_records = (
    step2_vut_df
    .join(
        diagnosis_tbl.filter(col("CODE").isin(e85_1_code)).filter(col("DATE").is_not_null()),
        on="PATIENT_ID"
    )
    .filter(col("DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID", col("CODE").alias("E85_1_CODE"), col("DATE").alias("E85_1_DATE"))
)

# ---- E85 group records (for the AND clause) ----
e85_group_records = (
    step2_vut_df
    .join(
        diagnosis_tbl.filter(col("CODE").isin(e85_group_codes)).filter(col("DATE").is_not_null()),
        on="PATIENT_ID"
    )
    .filter(col("DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID", col("CODE").alias("E85_CODE"), col("DATE").alias("E85_DATE"))
)

# ---- Neuropathy (G6x) records ----
neuro_records = (
    step2_vut_df
    .join(
        diagnosis_tbl.filter(col("CODE").isin(neuro_codes)).filter(col("DATE").is_not_null()),
        on="PATIENT_ID"
    )
    .filter(col("DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID", col("CODE").alias("NEURO_CODE"), col("DATE").alias("NEURO_DATE"))
)

In [74]:
# Patients meeting E85.1 criterion
pathway_a_patients = e85_1_records.select("PATIENT_ID").distinct()

# Patients meeting E85 group AND neuro group (any time apart)
e85_group_pairs = e85_group_records.join(neuro_records, on="PATIENT_ID", how="inner")
pathway_b_patients = e85_group_pairs.select("PATIENT_ID").distinct()

# Union of both pathways (patients meeting EITHER condition)
step3_patient_ids = pathway_a_patients.union(pathway_b_patients).distinct()

step3_vut_df = step2_vut_df.join(step3_patient_ids, on="PATIENT_ID", how="inner")
print(f"Step 3: {step3_vut_df.count()} patients")

Step 3: 340 patients

### Amyloidosis

In [75]:
# Population: patients meeting Step 3 (swap for step3a_df as needed)
population_ids = step3_vut_df.select("PATIENT_ID").distinct()

# Full amyloidosis code list for this table (E85.1 + E85 group)
all_amyloidosis_codes = ["E85.1", "E85", "E85.2", "E85.89", "E85.9"]

In [76]:
# AMYLOIDOSIS TABLE

# Distinct (PATIENT_ID, CODE) pairs for amyloidosis codes, restricted to population, <= index date
patient_amyloid_codes = (
    diagnosis_tbl
    .filter(col("CODE").isin(all_amyloidosis_codes))
    .filter(col("DATE").is_not_null())
    .join(step3_vut_df.select("PATIENT_ID", "INDEX_DATE"), on="PATIENT_ID", how="inner")
    .filter(col("DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID", col("CODE").alias("AMYLOID_CODE"))
    .distinct()
)

# How many distinct amyloidosis codes does each patient have?
patient_amyloid_code_counts = (
    patient_amyloid_codes
    .group_by("PATIENT_ID")
    .agg(count_distinct("AMYLOID_CODE").alias("N_DISTINCT_CODES"))
)

In [77]:
# ---- TABLE 1: >=1 code (any) ----
table_amyloid_any = (
    patient_amyloid_codes
    .group_by("AMYLOID_CODE")
    .agg(count_distinct("PATIENT_ID").alias("N_ANY"))
    .order_by(col("N_ANY").desc())
)
print("Amyloidosis Table 1: >=1 code (any)")
table_amyloid_any.show(20)

Amyloidosis Table 1: >=1 code (any)
----------------------------
|"AMYLOID_CODE"  |"N_ANY"  |
----------------------------
|E85.1           |307      |
|E85.9           |226      |
|E85.2           |199      |
|E85.89          |113      |
----------------------------

In [78]:
# ---- TABLE 2: only this code ----
only_amyloid_patients = (
    patient_amyloid_codes
    .join(patient_amyloid_code_counts, on="PATIENT_ID", how="inner")
    .filter(col("N_DISTINCT_CODES") == 1)
)

table_amyloid_only = (
    only_amyloid_patients
    .group_by("AMYLOID_CODE")
    .agg(count_distinct("PATIENT_ID").alias("N_ONLY"))
    .order_by(col("N_ONLY").desc())
)
print("Amyloidosis Table 2: only this code")
table_amyloid_only.show(20)

Amyloidosis Table 2: only this code
-----------------------------
|"AMYLOID_CODE"  |"N_ONLY"  |
-----------------------------
|E85.1           |51        |
|E85.9           |11        |
|E85.2           |3         |
|E85.89          |1         |
-----------------------------

### Neuropathy

In [79]:
patient_neuro_codes = (
    diagnosis_tbl
    .filter(col("CODE").isin(neuro_codes))
    .filter(col("DATE").is_not_null())
    .join(step3_vut_df.select("PATIENT_ID", "INDEX_DATE"), on="PATIENT_ID", how="inner")
    .filter(col("DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID", col("CODE").alias("NEURO_CODE"))
    .distinct()
)

patient_neuro_code_counts = (
    patient_neuro_codes
    .group_by("PATIENT_ID")
    .agg(count_distinct("NEURO_CODE").alias("N_DISTINCT_CODES"))
)

In [80]:
# ---- TABLE 1: >=1 code (any) ----
table_neuro_any = (
    patient_neuro_codes
    .group_by("NEURO_CODE")
    .agg(count_distinct("PATIENT_ID").alias("N_ANY"))
    .order_by(col("N_ANY").desc())
)
print("Neuropathy Table 1: >=1 code (any)")
table_neuro_any.show(20)

Neuropathy Table 1: >=1 code (any)
--------------------------
|"NEURO_CODE"  |"N_ANY"  |
--------------------------
|G63           |274      |
|G62.9         |230      |
|G60.9         |66       |
|G62.89        |63       |
|G60.3         |42       |
|G64           |1        |
--------------------------

In [81]:
# ---- TABLE 2: only this code ----
only_neuro_patients = (
    patient_neuro_codes
    .join(patient_neuro_code_counts, on="PATIENT_ID", how="inner")
    .filter(col("N_DISTINCT_CODES") == 1)
)

table_neuro_only = (
    only_neuro_patients
    .group_by("NEURO_CODE")
    .agg(count_distinct("PATIENT_ID").alias("N_ONLY"))
    .order_by(col("N_ONLY").desc())
)
print("Neuropathy Table 2: only this code")
table_neuro_only.show(20)

Neuropathy Table 2: only this code
---------------------------
|"NEURO_CODE"  |"N_ONLY"  |
---------------------------
|G63           |70        |
|G62.9         |29        |
|G62.89        |2         |
|G60.9         |1         |
|G60.3         |1         |
---------------------------

## Step 3a

In [82]:
# For pathway B, get first date of each per patient, then check 2-year window
e85_group_first = (
    e85_group_records
    .group_by("PATIENT_ID")
    .agg(s_min("E85_DATE").alias("E85_DATE_FIRST"))
)

neuro_first = (
    neuro_records
    .group_by("PATIENT_ID")
    .agg(s_min("NEURO_DATE").alias("NEURO_DATE_FIRST"))
)

pathway_b_within_2yr = (
    e85_group_first
    .join(neuro_first, on="PATIENT_ID", how="inner")
    .filter(s_abs(datediff("YEAR", col("E85_DATE_FIRST"), col("NEURO_DATE_FIRST"))) <= 2)
    .select("PATIENT_ID")
)

In [83]:
# Union: E85.1 pathway (no time restriction) OR pathway B within 2 years
step3a_patient_ids = pathway_a_patients.union(pathway_b_within_2yr).distinct()

step3a_vut_df = step2_vut_df.join(step3a_patient_ids, on="PATIENT_ID", how="inner")
print(f"Step 3a: {step3a_vut_df.count()} patients")

Step 3a: 335 patients

# Attrition table

## Vutrisiran

In [84]:
diagnosis_tbl = session.table("DATA_202511.DIAGNOSIS")
medication_tbl = session.table("DATA_202511.MEDICATION")

In [85]:
# ==================================================
# STEP 1: First vutrisiran on/after 2025-04-01
# ==================================================
step1_vut_att_df = (
    medication_tbl
    .filter(col("CODE_SYSTEM") == "RxNorm")
    .filter(col("CODE").isin(vutrisiran_codes))
    .filter(col("START_DATE") >= "2025-04-01")
    .filter(col("START_DATE").is_not_null())
    .group_by("PATIENT_ID")
    .agg(s_min("START_DATE").alias("INDEX_DATE"))
)
print(f"Step 1: {step1_vut_att_df.count()} patients")

Step 1: 605 patients

In [86]:
# ==================================================
# STEP 2: (E85.82 AND HF/CM code) OR tafamidis, any time prior to/on index
# ==================================================

# E85.82 records <= index
e85_82_records = (
    step1_vut_att_df
    .join(diagnosis_tbl.filter(col("CODE") == "E85.82").filter(col("DATE").is_not_null()), on="PATIENT_ID")
    .filter(col("DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID").distinct()
)

# CM/HF records <= index (reuse cm_codes_icd10 / cm_codes_icd9 from before)
cm_hf_records = (
    step1_vut_att_df
    .join(
        diagnosis_tbl.filter(
            (col("CODE_SYSTEM") == "ICD-10-CM") & col("CODE").isin(cm_codes_icd10)
            | (col("CODE_SYSTEM") == "ICD-9-CM") & col("CODE").isin(cm_codes_icd9)
        ).filter(col("DATE").is_not_null()),
        on="PATIENT_ID"
    )
    .filter(col("DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID").distinct()
)

# Pathway A: E85.82 AND CM/HF
pathway_a = e85_82_records.join(cm_hf_records, on="PATIENT_ID", how="inner")

# Pathway B: tafamidis any time prior to/on index
pathway_b = (
    step1_vut_att_df
    .join(
        medication_tbl.filter(col("CODE_SYSTEM") == "RxNorm").filter(col("CODE").isin(tafamidis_codes)),
        on="PATIENT_ID"
    )
    .filter(col("START_DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID").distinct()
)

step2_patient_ids = pathway_a.select("PATIENT_ID").union(pathway_b).distinct()
step2_vut_att_df = step1_vut_att_df.join(step2_patient_ids, on="PATIENT_ID", how="inner")
print(f"Step 2: {step2_vut_att_df.count()} patients")

Step 2: 527 patients

In [87]:
# ==================================================
# STEP 3: No vutrisiran any time prior to index
# ==================================================
prior_vutrisiran = (
    step2_vut_att_df
    .join(
        medication_tbl.filter(col("CODE_SYSTEM") == "RxNorm").filter(col("CODE").isin(vutrisiran_codes)),
        on="PATIENT_ID"
    )
    .filter(col("START_DATE") < col("INDEX_DATE"))
    .select("PATIENT_ID").distinct()
)

step3_vut_att_df = step2_vut_att_df.join(prior_vutrisiran, on="PATIENT_ID", how="anti")
print(f"Step 3: {step3_vut_att_df.count()} patients")

Step 3: 382 patients

In [88]:
acoramidis_codes = list(pd.read_excel("Aco_Vutri_TriNetX_Feas._codelists_JUL2026.xlsx", sheet_name = "Acoramidis")["rxcui"])
acoramidis_codes = [str(code) for code in acoramidis_codes ]

In [89]:
# ==================================================
# STEP 4: No acoramidis any time prior to/on index
# ==================================================
prior_acoramidis = (
    step3_vut_att_df
    .join(
        medication_tbl.filter(col("CODE_SYSTEM") == "RxNorm").filter(col("CODE").isin(acoramidis_codes)),
        on="PATIENT_ID"
    )
    .filter(col("START_DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID").distinct()
)

step4_vut_att_df = step3_vut_att_df.join(prior_acoramidis, on="PATIENT_ID", how="anti")
print(f"Step 4: {step4_vut_att_df.count()} patients")

Step 4: 360 patients

In [90]:
# step4_df here = the population of 360 (before step 5's 3mo exclusion)
taf_records = (
    step4_vut_att_df
    .join(
        medication_tbl.filter(col("CODE_SYSTEM") == "RxNorm").filter(col("CODE").isin(tafamidis_codes)),
        on="PATIENT_ID"
    )
    .filter(col("START_DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID", col("START_DATE").alias("TAF_DATE"), "INDEX_DATE")
)

total_n = step4_vut_att_df.select("PATIENT_ID").distinct().count()
print(f"Population (Step 4): {total_n} patients")

# Within 1 month prior to or on index
n_1mo = (
    taf_records
    .filter(datediff("DAY", col("TAF_DATE"), col("INDEX_DATE")) <= 30)
    .select("PATIENT_ID").distinct().count()
)
print(f"Tafamidis exposure within 1 month prior to or on index: {n_1mo}")

# Within 2 months prior to or on index
n_2mo = (
    taf_records
    .filter(datediff("DAY", col("TAF_DATE"), col("INDEX_DATE")) <= 60)
    .select("PATIENT_ID").distinct().count()
)
print(f"Tafamidis exposure within 2 months prior to or on index: {n_2mo}")

# For reference: within 3 months (should match your known n=185)
n_3mo = (
    taf_records
    .filter(datediff("DAY", col("TAF_DATE"), col("INDEX_DATE")) <= 90)
    .select("PATIENT_ID").distinct().count()
)
print(f"Tafamidis exposure within 3 months prior to or on index: {n_3mo}")

# On index exactly (should match your known n=25)
n_on_index = (
    taf_records
    .filter(col("TAF_DATE") == col("INDEX_DATE"))
    .select("PATIENT_ID").distinct().count()
)
print(f"Tafamidis exposure exactly on index: {n_on_index}")

Population (Step 4): 360 patients
Tafamidis exposure within 1 month prior to or on index: 110
Tafamidis exposure within 2 months prior to or on index: 140
Tafamidis exposure within 3 months prior to or on index: 170
Tafamidis exposure exactly on index: 25

In [91]:
# ==================================================
# STEP 5 / 5a: No tafamidis within 3 / 12 months prior to or on index
# ==================================================

tafamidis_records_step4 = (
    step4_vut_att_df
    .join(
        medication_tbl.filter(col("CODE_SYSTEM") == "RxNorm").filter(col("CODE").isin(tafamidis_codes)),
        on="PATIENT_ID"
    )
    .filter(col("START_DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID", "INDEX_DATE", col("START_DATE").alias("TAF_DATE"))
)

# 3-month window
tafamidis_3mo = (
    tafamidis_records_step4
    .filter(datediff("MONTH", col("TAF_DATE"), col("INDEX_DATE")) <= 3)
    .select("PATIENT_ID").distinct()
)
step5_vut_att_df = step4_vut_att_df.join(tafamidis_3mo, on="PATIENT_ID", how="anti")
print(f"Step 5: {step5_vut_att_df.count()} patients")

# 12-month window
tafamidis_12mo = (
    tafamidis_records_step4
    .filter(datediff("MONTH", col("TAF_DATE"), col("INDEX_DATE")) <= 12)
    .select("PATIENT_ID").distinct()
)
step5a_vut_att_df = step4_vut_att_df.join(tafamidis_12mo, on="PATIENT_ID", how="anti")
print(f"Step 5a: {step5a_vut_att_df.count()} patients")

Step 5: 185 patients
Step 5a: 80 patients

In [92]:
# ==================================================
# STEP 6 / 6a: No E85.81 (AL) any time prior to/on index
# ==================================================

def exclude_e85_81(df):
    e85_81_records = (
        df
        .join(diagnosis_tbl.filter(col("CODE") == "E85.81").filter(col("DATE").is_not_null()), on="PATIENT_ID")
        .filter(col("DATE") <= col("INDEX_DATE"))
        .select("PATIENT_ID").distinct()
    )
    return df.join(e85_81_records, on="PATIENT_ID", how="anti")

step6_vut_att_df = exclude_e85_81(step5_vut_att_df)
print(f"Step 6: {step6_vut_att_df.count()} patients")

step6a_vut_att_df = exclude_e85_81(step5a_vut_att_df)
print(f"Step 6a: {step6a_vut_att_df.count()} patients")

Step 6: 176 patients
Step 6a: 76 patients

In [93]:
# ==================================================
# STEP 7 / 7a: No hATTR-PN codes (neuro_codes) nor eplontersen/patisiran/inotersen, any time prior to/on index
# ==================================================

other_neuro_drugs = eplontersen_codes + inotersen_codes + patisiran_codes

def exclude_hattr_pn(df):
    # Neuropathy diagnosis codes
    neuro_dx = (
        df
        .join(diagnosis_tbl.filter(col("CODE").isin(neuro_codes)).filter(col("DATE").is_not_null()), on="PATIENT_ID")
        .filter(col("DATE") <= col("INDEX_DATE"))
        .select("PATIENT_ID").distinct()
    )

    # Other TTR drugs
    other_drugs = (
        df
        .join(
            medication_tbl.filter(col("CODE_SYSTEM") == "RxNorm").filter(col("CODE").isin(other_neuro_drugs)),
            on="PATIENT_ID"
        )
        .filter(col("START_DATE") <= col("INDEX_DATE"))
        .select("PATIENT_ID").distinct()
    )

    exclusions = neuro_dx.union(other_drugs).distinct()
    return df.join(exclusions, on="PATIENT_ID", how="anti")

step7_vut_att_df = exclude_hattr_pn(step6_vut_att_df)
print(f"Step 7: {step7_vut_att_df.count()} patients")

step7a_vut_att_df = exclude_hattr_pn(step6a_vut_att_df)
print(f"Step 7a: {step7a_vut_att_df.count()} patients")

Step 7: 115 patients
Step 7a: 47 patients

In [94]:
# Monthly counts for Step 7 cohort
step7_vut_att_monthly = (
    step7_vut_att_df
    .with_column("INDEX_MONTH", to_char(date_trunc("MONTH", col("INDEX_DATE")), "YYYY-MM"))
    .group_by("INDEX_MONTH")
    .agg(count_distinct("PATIENT_ID").alias("N_PATIENTS"))
    .order_by("INDEX_MONTH")
)
print("Step 7 — patients by index month:")
step7_vut_att_monthly.show(50)

Step 7 — patients by index month:
--------------------------------
|"INDEX_MONTH"  |"N_PATIENTS"  |
--------------------------------
|2025-04        |17            |
|2025-05        |18            |
|2025-06        |23            |
|2025-07        |22            |
|2025-08        |20            |
|2025-09        |11            |
|2025-10        |4             |
--------------------------------

## Acoramidis

In [95]:
# ==================================================
# STEP 1: First acoramidis on/after 2025-04-01
# ==================================================
step1_aco_att_df = (
    medication_tbl
    .filter(col("CODE_SYSTEM") == "RxNorm")
    .filter(col("CODE").isin(acoramidis_codes))
    .filter(col("START_DATE") >= "2025-04-01")
    .filter(col("START_DATE").is_not_null())
    .group_by("PATIENT_ID")
    .agg(s_min("START_DATE").alias("INDEX_DATE"))
)
print(f"Step 1: {step1_aco_att_df.count()} patients")

Step 1: 166 patients

In [96]:
# ==================================================
# STEP 2: (E85.82 AND HF/CM code) OR tafamidis, any time prior to/on index
# ==================================================

# E85.82 records <= index
e85_82_records = (
    step1_aco_att_df
    .join(diagnosis_tbl.filter(col("CODE") == "E85.82").filter(col("DATE").is_not_null()), on="PATIENT_ID")
    .filter(col("DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID").distinct()
)

# CM/HF records <= index (reuse cm_codes_icd10 / cm_codes_icd9 from before)
cm_hf_records = (
    step1_aco_att_df
    .join(
        diagnosis_tbl.filter(
            (col("CODE_SYSTEM") == "ICD-10-CM") & col("CODE").isin(cm_codes_icd10)
            | (col("CODE_SYSTEM") == "ICD-9-CM") & col("CODE").isin(cm_codes_icd9)
        ).filter(col("DATE").is_not_null()),
        on="PATIENT_ID"
    )
    .filter(col("DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID").distinct()
)

# Pathway A: E85.82 AND CM/HF
pathway_a = e85_82_records.join(cm_hf_records, on="PATIENT_ID", how="inner")

# Pathway B: tafamidis any time prior to/on index
pathway_b = (
    step1_aco_att_df
    .join(
        medication_tbl.filter(col("CODE_SYSTEM") == "RxNorm").filter(col("CODE").isin(tafamidis_codes)),
        on="PATIENT_ID"
    )
    .filter(col("START_DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID").distinct()
)

step2_patient_ids = pathway_a.select("PATIENT_ID").union(pathway_b).distinct()
step2_aco_att_df = step1_aco_att_df.join(step2_patient_ids, on="PATIENT_ID", how="inner")
print(f"Step 2: {step2_aco_att_df.count()} patients")

Step 2: 144 patients

In [97]:
# ==================================================
# STEP 3: No acoramidis any time prior to index
# ==================================================
prior_acoramidis = (
    step2_aco_att_df
    .join(
        medication_tbl.filter(col("CODE_SYSTEM") == "RxNorm").filter(col("CODE").isin(acoramidis_codes)),
        on="PATIENT_ID"
    )
    .filter(col("START_DATE") < col("INDEX_DATE"))
    .select("PATIENT_ID").distinct()
)

step3_aco_att_df = step2_aco_att_df.join(prior_acoramidis, on="PATIENT_ID", how="anti")
print(f"Step 3: {step3_aco_att_df.count()} patients")

Step 3: 104 patients

In [98]:
# ==================================================
# STEP 4: No vutrisiran any time prior to/on index
# ==================================================
prior_vutrisiran = (
    step3_aco_att_df
    .join(
        medication_tbl.filter(col("CODE_SYSTEM") == "RxNorm").filter(col("CODE").isin(vutrisiran_codes)),
        on="PATIENT_ID"
    )
    .filter(col("START_DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID").distinct()
)

step4_aco_att_df = step3_aco_att_df.join(prior_vutrisiran, on="PATIENT_ID", how="anti")
print(f"Step 4: {step4_aco_att_df.count()} patients")

Step 4: 102 patients

In [99]:
# step4_df here = the population of 360 (before step 5's 3mo exclusion)
taf_records = (
    step4_aco_att_df
    .join(
        medication_tbl.filter(col("CODE_SYSTEM") == "RxNorm").filter(col("CODE").isin(tafamidis_codes)),
        on="PATIENT_ID"
    )
    .filter(col("START_DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID", col("START_DATE").alias("TAF_DATE"), "INDEX_DATE")
)

total_n = step4_aco_att_df.select("PATIENT_ID").distinct().count()
print(f"Population (Step 4): {total_n} patients")

# Within 1 month prior to or on index
n_1mo = (
    taf_records
    .filter(datediff("DAY", col("TAF_DATE"), col("INDEX_DATE")) <= 30)
    .select("PATIENT_ID").distinct().count()
)
print(f"Tafamidis exposure within 1 month prior to or on index: {n_1mo}")

# Within 2 months prior to or on index
n_2mo = (
    taf_records
    .filter(datediff("DAY", col("TAF_DATE"), col("INDEX_DATE")) <= 60)
    .select("PATIENT_ID").distinct().count()
)
print(f"Tafamidis exposure within 2 months prior to or on index: {n_2mo}")

# For reference: within 3 months (should match your known n=185)
n_3mo = (
    taf_records
    .filter(datediff("DAY", col("TAF_DATE"), col("INDEX_DATE")) <= 90)
    .select("PATIENT_ID").distinct().count()
)
print(f"Tafamidis exposure within 3 months prior to or on index: {n_3mo}")

# On index exactly (should match your known n=25)
n_on_index = (
    taf_records
    .filter(col("TAF_DATE") == col("INDEX_DATE"))
    .select("PATIENT_ID").distinct().count()
)
print(f"Tafamidis exposure exactly on index: {n_on_index}")

Population (Step 4): 102 patients
Tafamidis exposure within 1 month prior to or on index: 25
Tafamidis exposure within 2 months prior to or on index: 30
Tafamidis exposure within 3 months prior to or on index: 39
Tafamidis exposure exactly on index: 5

In [100]:
# ==================================================
# STEP 5 / 5a: No tafamidis within 3 / 12 months prior to or on index
# ==================================================

tafamidis_records_step4 = (
    step4_aco_att_df
    .join(
        medication_tbl.filter(col("CODE_SYSTEM") == "RxNorm").filter(col("CODE").isin(tafamidis_codes)),
        on="PATIENT_ID"
    )
    .filter(col("START_DATE") <= col("INDEX_DATE"))
    .select("PATIENT_ID", "INDEX_DATE", col("START_DATE").alias("TAF_DATE"))
)

# 3-month window
tafamidis_3mo = (
    tafamidis_records_step4
    .filter(datediff("MONTH", col("TAF_DATE"), col("INDEX_DATE")) <= 3)
    .select("PATIENT_ID").distinct()
)
step5_aco_att_df = step4_aco_att_df.join(tafamidis_3mo, on="PATIENT_ID", how="anti")
print(f"Step 5: {step5_aco_att_df.count()} patients")

# 12-month window
tafamidis_12mo = (
    tafamidis_records_step4
    .filter(datediff("MONTH", col("TAF_DATE"), col("INDEX_DATE")) <= 12)
    .select("PATIENT_ID").distinct()
)
step5a_aco_att_df = step4_aco_att_df.join(tafamidis_12mo, on="PATIENT_ID", how="anti")
print(f"Step 5a: {step5a_aco_att_df.count()} patients")

Step 5: 62 patients
Step 5a: 40 patients

In [101]:
# ==================================================
# STEP 6 / 6a: No E85.81 (AL) any time prior to/on index
# ==================================================

def exclude_e85_81(df):
    e85_81_records = (
        df
        .join(diagnosis_tbl.filter(col("CODE") == "E85.81").filter(col("DATE").is_not_null()), on="PATIENT_ID")
        .filter(col("DATE") <= col("INDEX_DATE"))
        .select("PATIENT_ID").distinct()
    )
    return df.join(e85_81_records, on="PATIENT_ID", how="anti")

step6_aco_att_df = exclude_e85_81(step5_aco_att_df)
print(f"Step 6: {step6_aco_att_df.count()} patients")

step6a_aco_att_df = exclude_e85_81(step5a_aco_att_df)
print(f"Step 6a: {step6a_aco_att_df.count()} patients")

Step 6: 62 patients
Step 6a: 40 patients

In [102]:
# ==================================================
# STEP 7 / 7a: No hATTR-PN codes (neuro_codes) nor eplontersen/patisiran/inotersen, any time prior to/on index
# ==================================================

other_neuro_drugs = eplontersen_codes + inotersen_codes + patisiran_codes

def exclude_hattr_pn(df):
    # Neuropathy diagnosis codes
    neuro_dx = (
        df
        .join(diagnosis_tbl.filter(col("CODE").isin(neuro_codes)).filter(col("DATE").is_not_null()), on="PATIENT_ID")
        .filter(col("DATE") <= col("INDEX_DATE"))
        .select("PATIENT_ID").distinct()
    )

    # Other TTR drugs
    other_drugs = (
        df
        .join(
            medication_tbl.filter(col("CODE_SYSTEM") == "RxNorm").filter(col("CODE").isin(other_neuro_drugs)),
            on="PATIENT_ID"
        )
        .filter(col("START_DATE") <= col("INDEX_DATE"))
        .select("PATIENT_ID").distinct()
    )

    exclusions = neuro_dx.union(other_drugs).distinct()
    return df.join(exclusions, on="PATIENT_ID", how="anti")

step7_aco_att_df = exclude_hattr_pn(step6_aco_att_df)
print(f"Step 7: {step7_aco_att_df.count()} patients")

step7a_aco_att_df = exclude_hattr_pn(step6a_aco_att_df)
print(f"Step 7a: {step7a_aco_att_df.count()} patients")

Step 7: 51 patients
Step 7a: 34 patients

In [103]:
# Monthly counts for Step 7 cohort
step7_aco_att_monthly = (
    step7_aco_att_df
    .with_column("INDEX_MONTH", to_char(date_trunc("MONTH", col("INDEX_DATE")), "YYYY-MM"))
    .group_by("INDEX_MONTH")
    .agg(count_distinct("PATIENT_ID").alias("N_PATIENTS"))
    .order_by("INDEX_MONTH")
)
print("Step 7 — patients by index month:")
step7_aco_att_monthly.show(50)

Step 7 — patients by index month:
--------------------------------
|"INDEX_MONTH"  |"N_PATIENTS"  |
--------------------------------
|2025-04        |14            |
|2025-05        |8             |
|2025-06        |8             |
|2025-07        |6             |
|2025-08        |5             |
|2025-09        |4             |
|2025-10        |6             |
--------------------------------

# Baseline characteristics

In [104]:
patient_tbl = session.table("DATA_202511.PATIENT")
lab_tbl = session.table("DATA_202511.LAB_RESULT")

In [105]:
egfr_codes = pd.read_excel(
    "Aco_Vutri_TriNetX_Feas._codelists_JUL2026.xlsx",
    sheet_name="eGFR",
    skiprows=1
)["Code"].dropna().astype(str).tolist()
egfr_codes

['98979-8',
 '98980-6',
 '50210-4',
 '102097-3',
 '77147-7',
 '48642-3',
 '48643-1',
 '50044-7',
 '50384-7',
 '62238-1',
 '69405-9',
 '70969-1',
 '77147-7',
 '88293-6',
 '88294-4',
 '94677-2',
 '33914-3',
 '76633-7',
 '97952-6',
 '50383-9',
 '96591-3',
 '96592-1',
 '50383-9']

In [106]:
ntprobnp_codes = list(pd.read_excel("Aco_Vutri_TriNetX_Feas._codelists_JUL2026.xlsx", sheet_name = "NT-proBNP", skiprows=1)["Code"].dropna())
ntprobnp_codes = [str(code) for code in ntprobnp_codes]

In [107]:
furosemideiv_codes = list(pd.read_excel("Aco_Vutri_TriNetX_Feas._codelists_JUL2026.xlsx", sheet_name = ' Furosemide IV', skiprows=1)["Code"].dropna())
furosemideiv_codes = [str(code) for code in furosemideiv_codes]

In [108]:
furosemideoral_codes = list(pd.read_excel("Aco_Vutri_TriNetX_Feas._codelists_JUL2026.xlsx", sheet_name = 'Furosemide Oral', skiprows=1)["Code"].dropna())
furosemideoral_codes = [str(code) for code in furosemideoral_codes]

In [109]:
torsemideiv_codes = list(pd.read_excel("Aco_Vutri_TriNetX_Feas._codelists_JUL2026.xlsx", sheet_name = 'Torsemide IV', skiprows=1)["Code"].dropna())
torsemideiv_codes = [str(code) for code in torsemideiv_codes]

In [110]:
torsemideoral_codes = list(pd.read_excel("Aco_Vutri_TriNetX_Feas._codelists_JUL2026.xlsx", sheet_name = 'Torsemide Oral', skiprows=1)["Code"].dropna())
torsemideoral_codes = [str(code) for code in torsemideoral_codes]

In [111]:
bumetanideiv_codes = list(pd.read_excel("Aco_Vutri_TriNetX_Feas._codelists_JUL2026.xlsx", sheet_name = 'Bumetanide IV', skiprows=1)["Code"].dropna())
bumetanideiv_codes = [str(code) for code in bumetanideiv_codes]

In [112]:
bumetanideoral_codes = list(pd.read_excel("Aco_Vutri_TriNetX_Feas._codelists_JUL2026.xlsx", sheet_name = 'Bumetanide Oral', skiprows=1)["Code"].dropna())
bumetanideoral_codes = [str(code) for code in bumetanideoral_codes]

In [113]:
loop_diuretic_codes = furosemideiv_codes + furosemideoral_codes + torsemideiv_codes + torsemideoral_codes + bumetanideiv_codes + bumetanideoral_codes

In [114]:
session.table("DATA_202511.DRUG").filter(col("CODE").isin(tafamidis_codes)).show()

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"PATIENT_ID"  |"ENCOUNTER_ID"  |"UNIQUE_ID"  |"CODE_SYSTEM"  |"CODE"   |"START_DATE"  |"ROUTE"       |"BRAND"   |"STRENGTH"  |"QUANTITY_DISPENSED"  |"DAYS_SUPPLY"  |"DERIVED_BY_TRINETX"  |"SOURCE_ID"  |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|dAB           |gQXCe           |dAB          |RxNorm_drug    |2168548  |2021-01-29    |Oral Product  |Vyndaqel  |Unknown     |120.000000            |NULL           |False                 |EHR          |
|dQ            |gQaEk           |dAI          |RxNorm_drug    |2168540  |2025-01-20    |Oral Product  |Vyndamax  |Unknown     |90.000000             |NULL           |False                 |EHR          |
|dQ            |gwaEk           |dQI          |RxNorm_drug    |2168540  |2025-09-04    |Oral Product  |Vyndamax  |Unknown     |90.000000             |NULL           |False                 |EHR          |
|dg            |gAdEm           |dgU          |RxNorm_drug    |2168540  |2021-04-05    |Oral Product  |Vyndamax  |Unknown     |0.000000              |NULL           |False                 |EHR          |
|Fg            |IwJ             |FgNC         |RxNorm_drug    |2168540  |2020-06-13    |Oral Product  |Vyndamax  |Unknown     |30.000000             |30             |False                 |EHR          |
|Fg            |IwJ             |FwNC         |RxNorm_drug    |2168540  |2020-06-13    |Oral Product  |Vyndamax  |Unknown     |30.000000             |30             |False                 |EHR          |
|Fw            |IgO             |FAuD         |RxNorm_drug    |2168540  |2021-12-01    |Oral Product  |Vyndamax  |Unknown     |30.000000             |30             |False                 |EHR          |
|Fw            |IQS             |FQuD         |RxNorm_drug    |2168540  |2021-12-01    |Oral Product  |Vyndamax  |Unknown     |30.000000             |30             |False                 |EHR          |
|ERg           |HRSNPK          |EBiC         |RxNorm_drug    |2168534  |2024-05-13    |Oral Product  |Unknown   |Unknown     |NULL                  |NULL           |False                 |EHR          |
|ERi           |HxtGbM          |ERCQ         |RxNorm_drug    |2168534  |2024-05-08    |Oral Product  |Unknown   |Unknown     |NULL                  |NULL           |False                 |EHR          |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [148]:
session.sql("USE SCHEMA DATA_202511").collect()

[Row(status='Statement executed successfully.')]

In [149]:
from snowflake.snowpark.functions import (
    col, count, count_distinct, avg, stddev, median, when, lit,
    row_number, percentile_cont, datediff, min as spark_min
)
from snowflake.snowpark import Window
import pandas as pd

patient_tbl = session.table("DATA_202511.PATIENT")
lab_tbl = session.table("DATA_202511.LAB_RESULT")
medication_tbl = session.table("DATA_202511.MEDICATION")
diagnosis_tbl = session.table("DATA_202511.DIAGNOSIS")
encounter_tbl = session.table("DATA_202511.ENCOUNTER")
drug_tbl = session.table("DATA_202511.DRUG")

# NOTE: assumes these are already defined globally:
# ntprobnp_codes, egfr_codes, tafamidis_codes, neuro_codes (G6x list), 
# cm_codes_icd10 / cm_codes_icd9 (HF/CM codes), loop_diuretic_codes

def get_baseline_characteristics(cohort_df, cohort_label="Cohort"):
    from builtins import round as py_round
    cohort_df = cohort_df.cache_result()
    total_n = cohort_df.select("PATIENT_ID").distinct().count()
    print(f"\n=== {cohort_label} (N={total_n}) ===")

    results = {}
    index_dates = cohort_df.select("PATIENT_ID", "INDEX_DATE").to_pandas()
    index_dates["INDEX_DATE"] = pd.to_datetime(index_dates["INDEX_DATE"])

    # ==================================================
    # AGE (unchanged)
    # ==================================================
    age_df = (
        cohort_df
        .join(patient_tbl.select("PATIENT_ID", "YEAR_OF_BIRTH"), on="PATIENT_ID", how="left")
        .with_column(
            "AGE",
            when(col("YEAR_OF_BIRTH").is_not_null(),
                 (col("INDEX_DATE").cast("date").substr(1, 4).cast("int") - col("YEAR_OF_BIRTH")))
            .otherwise(lit(None))
        )
    )
    age_stats = age_df.agg(
        avg("AGE").alias("MEAN_AGE"), stddev("AGE").alias("SD_AGE"), median("AGE").alias("MEDIAN_AGE"),
        percentile_cont(0.25).within_group("AGE").alias("Q1"),
        percentile_cont(0.75).within_group("AGE").alias("Q3"),
        count(when(col("AGE").is_null(), 1)).alias("N_MISSING"),
        count(when(col("AGE") < 80, 1)).alias("N_UNDER_80"),
    ).to_pandas()
    age_stats["N_TOTAL"] = total_n
    age_stats["PCT_UNDER_80"] = (100 * age_stats["N_UNDER_80"] / total_n).round(1)
    age_stats["PCT_MISSING"] = (100 * age_stats["N_MISSING"] / total_n).round(1)
    print("\nAge:"); print(age_stats)
    results["age"] = age_stats

    # ==================================================
    # SEX (unchanged)
    # ==================================================
    sex_stats = (
        cohort_df.join(patient_tbl.select("PATIENT_ID", "SEX"), on="PATIENT_ID", how="left")
        .group_by("SEX").agg(count_distinct("PATIENT_ID").alias("N")).to_pandas()
    )
    sex_stats["PCT"] = (100 * sex_stats["N"] / total_n).round(1)
    print("\nSex:"); print(sex_stats)
    results["sex"] = sex_stats

    # ==================================================
    # Pull NT-proBNP and eGFR ONCE (<=12mo), reuse for NAC + individual breakdowns
    # ==================================================
    ntprobnp_12mo = (
        cohort_df
        .join(lab_tbl.filter(col("CODE").isin(ntprobnp_codes)).filter(col("LAB_RESULT_NUM_VAL").is_not_null()),
              on="PATIENT_ID")
        .filter(col("DATE") <= col("INDEX_DATE"))
        .filter(datediff("MONTH", col("DATE"), col("INDEX_DATE")) <= 12)
        .select("PATIENT_ID", "DATE", col("LAB_RESULT_NUM_VAL").alias("NTPROBNP_VAL"))
        .to_pandas()
    )
    ntprobnp_12mo["DATE"] = pd.to_datetime(ntprobnp_12mo["DATE"])

    egfr_12mo = (
        cohort_df
        .join(lab_tbl.filter(col("CODE").isin(egfr_codes)).filter(col("LAB_RESULT_NUM_VAL").is_not_null()),
              on="PATIENT_ID")
        .filter(col("DATE") <= col("INDEX_DATE"))
        .filter(datediff("MONTH", col("DATE"), col("INDEX_DATE")) <= 12)
        .select("PATIENT_ID", "DATE", col("LAB_RESULT_NUM_VAL").alias("EGFR_VAL"))
        .to_pandas()
    )
    egfr_12mo["DATE"] = pd.to_datetime(egfr_12mo["DATE"])

    def get_latest_in_window(lab_df, val_col, window_months):
        merged = lab_df.merge(index_dates, on="PATIENT_ID")
        merged["MONTHS_DIFF"] = (merged["INDEX_DATE"] - merged["DATE"]).dt.days / 30.44
        merged = merged[merged["MONTHS_DIFF"] <= window_months]
        latest = merged.sort_values("DATE").groupby("PATIENT_ID").tail(1)[["PATIENT_ID", "DATE", val_col]]
        return index_dates[["PATIENT_ID"]].merge(latest, on="PATIENT_ID", how="left")

    # ---- NAC Stage (with pairing definition: max allowed gap between NT-proBNP and eGFR dates) ----
    def get_nac_stage_pandas(window_months, max_gap_months):
        """
        window_months: lookback window for each lab (closest to/prior to index, within this window)
        max_gap_months: max allowed time between the NT-proBNP date and eGFR date for them 
                         to be used together in the same NAC calculation
        """
        nt = get_latest_in_window(ntprobnp_12mo, "NTPROBNP_VAL", window_months)
        eg = get_latest_in_window(egfr_12mo, "EGFR_VAL", window_months)
    
        # nt/eg currently only have PATIENT_ID + value column (from get_latest_in_window,
        # which returns index_dates[["PATIENT_ID"]].merge(latest, ...))
        # We need the actual lab DATE too, so pull from the "latest" step directly instead:
        nt_dated = get_latest_in_window(ntprobnp_12mo, "NTPROBNP_VAL", window_months)
        eg_dated = get_latest_in_window(egfr_12mo, "EGFR_VAL", window_months)
    
        combined = nt_dated.merge(eg_dated, on="PATIENT_ID", how="left")
    
        # Compute gap in months between the two lab dates (only relevant where both exist)
        combined["GAP_DAYS"] = (combined["DATE_x"] - combined["DATE_y"]).abs().dt.days
        combined["GAP_MONTHS"] = combined["GAP_DAYS"] / 30.44
    
        def stage(row):
            if pd.isna(row["NTPROBNP_VAL"]) or pd.isna(row["EGFR_VAL"]):
                return "Unclassified"
            if row["GAP_MONTHS"] > max_gap_months:
                return "Unclassified"  # too far apart to pair together
            if row["NTPROBNP_VAL"] <= 3000 and row["EGFR_VAL"] >= 45:
                return "Stage I"
            if row["NTPROBNP_VAL"] > 3000 and row["EGFR_VAL"] < 45:
                return "Stage III"
            return "Stage II"
    
        combined["NAC_STAGE"] = combined.apply(stage, axis=1)
        out = combined.groupby("NAC_STAGE")["PATIENT_ID"].nunique().reset_index(name="N")
        out["PCT"] = (100 * out["N"] / total_n).round(1)
        return out
    
    # 6-month window, Definition 1 (≤3mo gap) and Definition 2 (≤6mo gap)
    nac_6mo_def1 = get_nac_stage_pandas(window_months=6, max_gap_months=3)
    print("\nNAC Stage (within 6 months, Definition 1 - max 3mo gap):"); print(nac_6mo_def1)
    results["nac_6mo_def1"] = nac_6mo_def1
    
    nac_6mo_def2 = get_nac_stage_pandas(window_months=6, max_gap_months=6)
    print("\nNAC Stage (within 6 months, Definition 2 - max 6mo gap):"); print(nac_6mo_def2)
    results["nac_6mo_def2"] = nac_6mo_def2
    
    # 12-month window, Definition 1 (≤3mo gap) and Definition 2 (≤6mo gap)
    nac_12mo_def1 = get_nac_stage_pandas(window_months=12, max_gap_months=3)
    print("\nNAC Stage (within 12 months, Definition 1 - max 3mo gap):"); print(nac_12mo_def1)
    results["nac_12mo_def1"] = nac_12mo_def1
    
    nac_12mo_def2 = get_nac_stage_pandas(window_months=12, max_gap_months=6)
    print("\nNAC Stage (within 12 months, Definition 2 - max 6mo gap):"); print(nac_12mo_def2)
    results["nac_12mo_def2"] = nac_12mo_def2

    # ==================================================
    # NT-proBNP categorical breakdown (6mo / 12mo)
    # ==================================================
    def categorize_ntprobnp(window_months):
        nt = get_latest_in_window(ntprobnp_12mo, "NTPROBNP_VAL", window_months)
        nt["CATEGORY"] = pd.cut(
            nt["NTPROBNP_VAL"], bins=[-float("inf"), 3000, float("inf")],
            labels=["≤3,000", ">3,000"]
        )
        nt["CATEGORY"] = nt["CATEGORY"].astype(object).where(nt["NTPROBNP_VAL"].notna(), "Missing")
        out = nt.groupby("CATEGORY", observed=True)["PATIENT_ID"].nunique().reset_index(name="N")
        out["PCT"] = (100 * out["N"] / total_n).round(1)
        return out

    ntprobnp_6mo_cat = categorize_ntprobnp(6)
    print("\nNT-proBNP within 6mo:"); print(ntprobnp_6mo_cat)
    results["ntprobnp_6mo"] = ntprobnp_6mo_cat

    ntprobnp_12mo_cat = categorize_ntprobnp(12)
    print("\nNT-proBNP within 12mo:"); print(ntprobnp_12mo_cat)
    results["ntprobnp_12mo"] = ntprobnp_12mo_cat

    # ==================================================
    # eGFR categorical breakdown (6mo / 12mo)
    # ==================================================
    def categorize_egfr(window_months):
        eg = get_latest_in_window(egfr_12mo, "EGFR_VAL", window_months)
        eg["CATEGORY"] = pd.cut(
            eg["EGFR_VAL"], bins=[-float("inf"), 45, float("inf")],
            labels=["<45", "≥45"], right=False
        )
        eg["CATEGORY"] = eg["CATEGORY"].astype(object).where(eg["EGFR_VAL"].notna(), "Missing")
        out = eg.groupby("CATEGORY", observed=True)["PATIENT_ID"].nunique().reset_index(name="N")
        out["PCT"] = (100 * out["N"] / total_n).round(1)
        return out

    egfr_6mo_cat = categorize_egfr(6)
    print("\neGFR within 6mo:"); print(egfr_6mo_cat)
    results["egfr_6mo"] = egfr_6mo_cat

    egfr_12mo_cat = categorize_egfr(12)
    print("\neGFR within 12mo:"); print(egfr_12mo_cat)
    results["egfr_12mo"] = egfr_12mo_cat

    # ==================================================
    # hATTR-PN (any time prior to or on index)
    # ==================================================
    hattr_pn_patients = (
        cohort_df
        .join(diagnosis_tbl.filter(col("CODE").isin(neuro_codes)).filter(col("DATE").is_not_null()),
              on="PATIENT_ID")
        .filter(col("DATE") <= col("INDEX_DATE"))
        .select("PATIENT_ID").distinct()
    )
    n_hattr_pn = hattr_pn_patients.count()
    hattr_pn_stats = pd.DataFrame([{
        "N": n_hattr_pn, "PCT": builtins.round(100 * n_hattr_pn / total_n, 1)
    }])
    print("\nhATTR-PN (any time, Yes):"); print(hattr_pn_stats)
    results["hattr_pn"] = hattr_pn_stats

    # ==================================================
    # HHF (Hospitalization for Heart Failure)
    # ASSUMPTION: inpatient encounter (ENCOUNTER.TYPE) with an HF/CM diagnosis on that encounter
    # *** Please confirm what values ENCOUNTER.TYPE takes for inpatient stays (e.g. 'inpatient') ***
    # ==================================================
    hf_dx_on_encounter = (
        diagnosis_tbl
        .filter(
            (col("CODE_SYSTEM") == "ICD-10-CM") & col("CODE").isin(cm_codes_icd10)
            | (col("CODE_SYSTEM") == "ICD-9-CM") & col("CODE").isin(cm_codes_icd9)
        )
        .select("ENCOUNTER_ID", "PATIENT_ID")
        .distinct()
    )

    hhf_encounters = (
        cohort_df
        .join(
            encounter_tbl.filter(col("TYPE") == "IMP"),  # Inpatient Encounter only
            on="PATIENT_ID"
        )
        .join(hf_dx_on_encounter, on=["PATIENT_ID", "ENCOUNTER_ID"], how="inner")
        .filter(col("START_DATE") <= col("INDEX_DATE"))
        .select("PATIENT_ID", col("START_DATE").alias("HHF_DATE"))
        .to_pandas()
    )
    hhf_encounters["HHF_DATE"] = pd.to_datetime(hhf_encounters["HHF_DATE"])

    if len(hhf_encounters) > 0:
        hhf_latest = hhf_encounters.merge(index_dates, on="PATIENT_ID").sort_values("HHF_DATE") \
            .groupby("PATIENT_ID").tail(1)
        hhf_latest["DAYS_DIFF"] = (hhf_latest["INDEX_DATE"] - hhf_latest["HHF_DATE"]).dt.days
    else:
        hhf_latest = pd.DataFrame(columns=["PATIENT_ID", "DAYS_DIFF"])

    def hhf_category(days_diff):
        if pd.isna(days_diff):
            return ">3mo or no HHF event"
        if days_diff <= 7:
            return "≤7 days prior to or on index"
        if days_diff <= 90:
            return ">7 days - ≤3mo prior to index"
        return ">3mo or no HHF event"

    hhf_full = index_dates[["PATIENT_ID"]].merge(
        hhf_latest[["PATIENT_ID", "DAYS_DIFF"]], on="PATIENT_ID", how="left"
    )
    hhf_full["HHF_CATEGORY"] = hhf_full["DAYS_DIFF"].apply(hhf_category)
    hhf_stats = hhf_full.groupby("HHF_CATEGORY")["PATIENT_ID"].nunique().reset_index(name="N")
    hhf_stats["PCT"] = (100 * hhf_stats["N"] / total_n).round(1)
    print("\nHHF:"); print(hhf_stats)
    results["hhf"] = hhf_stats

    # ==================================================
    # Tafamidis (ever) - any time, no date restriction
    # ==================================================
    tafamidis_ever_patients = (
        cohort_df
        .join(
            medication_tbl.filter(col("CODE_SYSTEM") == "RxNorm").filter(col("CODE").isin(tafamidis_codes)),
            on="PATIENT_ID"
        )
        .filter(col("START_DATE") <= col("INDEX_DATE"))
        .select("PATIENT_ID").distinct()
    )
    n_taf_ever = tafamidis_ever_patients.count()
    taf_stats = pd.DataFrame([{"N": n_taf_ever, "PCT": builtins.round(100 * n_taf_ever / total_n, 1)}])
    print("\nTafamidis (any time prior to or on index, Yes):"); print(taf_stats)
    results["tafamidis_prior_or_on_index"] = taf_stats

    # ==================================================
    # Loop diuretic (30 / 60 / 90 days prior to or on index)
    # NOTE: uses loop_diuretic_codes - confirm CODE_SYSTEM coverage (RxNorm ± HCPCS)
    # ==================================================
    loop_records = (
        cohort_df
        .join(
            drug_tbl.filter(col("CODE").isin(loop_diuretic_codes)),
            on="PATIENT_ID"
        )
        .filter(col("START_DATE") <= col("INDEX_DATE"))
        .select("PATIENT_ID", col("START_DATE").alias("LOOP_DATE"))
        .to_pandas()
    )
    loop_records["LOOP_DATE"] = pd.to_datetime(loop_records["LOOP_DATE"])
    loop_merged = loop_records.merge(index_dates, on="PATIENT_ID")
    loop_merged["DAYS_DIFF"] = (loop_merged["INDEX_DATE"] - loop_merged["LOOP_DATE"]).dt.days

    loop_stats_rows = []
    for days in [30, 60, 90]:
        n_patients = loop_merged[loop_merged["DAYS_DIFF"] <= days]["PATIENT_ID"].nunique()
        loop_stats_rows.append({
        "WINDOW": f"{days} days prior to or on index",
        "N": n_patients,
        "PCT": builtins.round(100 * n_patients / total_n, 1)
    })
    loop_stats = pd.DataFrame(loop_stats_rows)
    print("\nLoop diuretic:"); print(loop_stats)
    results["loop_diuretic"] = loop_stats

    return results

In [150]:
step7_vut_baseline = get_baseline_characteristics(step7_vut_att_df, cohort_label="Vutrisiran")

=== Vutrisiran (N=115) ===

Age:
    MEAN_AGE    SD_AGE  MEDIAN_AGE    Q1    Q3  N_MISSING  N_UNDER_80  \
0  78.892857  5.909768        79.0  74.0  83.0          3          58

   N_TOTAL  PCT_UNDER_80  PCT_MISSING
0      115          50.4          2.6

Sex:
  SEX    N   PCT
0   F   15  13.0
1   M  100  87.0

NAC Stage (within 6 months, Definition 1 - max 3mo gap):
      NAC_STAGE   N   PCT
0       Stage I  29  25.2
1      Stage II  18  15.7
2     Stage III   4   3.5
3  Unclassified  64  55.7

NAC Stage (within 6 months, Definition 2 - max 6mo gap):
      NAC_STAGE   N   PCT
0       Stage I  29  25.2
1      Stage II  20  17.4
2     Stage III   4   3.5
3  Unclassified  62  53.9

NAC Stage (within 12 months, Definition 1 - max 3mo gap):
      NAC_STAGE   N   PCT
0       Stage I  33  28.7
1      Stage II  20  17.4
2     Stage III   4   3.5
3  Unclassified  58  50.4

NAC Stage (within 12 months, Definition 2 - max 6mo gap):
      NAC_STAGE   N   PCT
0       Stage I  33  28.7
1      Stage II  22  19.1
2     Stage III   4   3.5
3  Unclassified  56  48.7

NT-proBNP within 6mo:
  CATEGORY   N   PCT
0   >3,000  13  11.3
1  Missing  59  51.3
2   ≤3,000  43  37.4

NT-proBNP within 12mo:
  CATEGORY   N   PCT
0   >3,000  15  13.0
1  Missing  50  43.5
2   ≤3,000  50  43.5

eGFR within 6mo:
  CATEGORY   N   PCT
0      <45  29  25.2
1  Missing  29  25.2
2      ≥45  57  49.6

eGFR within 12mo:
  CATEGORY   N   PCT
0      <45  32  27.8
1  Missing  19  16.5
2      ≥45  64  55.7

hATTR-PN (any time, Yes):
   N  PCT
0  0  0.0

HHF:
                    HHF_CATEGORY    N   PCT
0           >3mo or no HHF event  109  94.8
1  >7 days - ≤3mo prior to index    6   5.2

Tafamidis (any time prior to or on index, Yes):
    N   PCT
0  92  80.0

Loop diuretic:
                         WINDOW   N   PCT
0  30 days prior to or on index  11   9.6
1  60 days prior to or on index  21  18.3
2  90 days prior to or on index  26  22.6

In [151]:
step7_aco_baseline = get_baseline_characteristics(step7_aco_att_df, cohort_label="Acoramidis")

=== Acoramidis (N=51) ===

Age:
    MEAN_AGE    SD_AGE  MEDIAN_AGE    Q1    Q3  N_MISSING  N_UNDER_80  \
0  78.787234  6.423246        80.0  74.0  83.0          4          19

   N_TOTAL  PCT_UNDER_80  PCT_MISSING
0       51          37.3          7.8

Sex:
  SEX   N   PCT
0   M  43  84.3
1   F   8  15.7

NAC Stage (within 6 months, Definition 1 - max 3mo gap):
      NAC_STAGE   N   PCT
0       Stage I  10  19.6
1      Stage II   8  15.7
2     Stage III   5   9.8
3  Unclassified  28  54.9

NAC Stage (within 6 months, Definition 2 - max 6mo gap):
      NAC_STAGE   N   PCT
0       Stage I  12  23.5
1      Stage II   8  15.7
2     Stage III   5   9.8
3  Unclassified  26  51.0

NAC Stage (within 12 months, Definition 1 - max 3mo gap):
      NAC_STAGE   N   PCT
0       Stage I  10  19.6
1      Stage II  10  19.6
2     Stage III   4   7.8
3  Unclassified  27  52.9

NAC Stage (within 12 months, Definition 2 - max 6mo gap):
      NAC_STAGE   N   PCT
0       Stage I  13  25.5
1      Stage II  10  19.6
2     Stage III   4   7.8
3  Unclassified  24  47.1

NT-proBNP within 6mo:
  CATEGORY   N   PCT
0   >3,000  12  23.5
1  Missing  25  49.0
2   ≤3,000  14  27.5

NT-proBNP within 12mo:
  CATEGORY   N   PCT
0   >3,000  13  25.5
1  Missing  23  45.1
2   ≤3,000  15  29.4

eGFR within 6mo:
  CATEGORY   N   PCT
0      <45  10  19.6
1  Missing  12  23.5
2      ≥45  29  56.9

eGFR within 12mo:
  CATEGORY   N   PCT
0      <45   9  17.6
1  Missing   7  13.7
2      ≥45  35  68.6

hATTR-PN (any time, Yes):
   N  PCT
0  0  0.0

HHF:
                    HHF_CATEGORY   N   PCT
0           >3mo or no HHF event  43  84.3
1  >7 days - ≤3mo prior to index   2   3.9
2   ≤7 days prior to or on index   6  11.8

Tafamidis (any time prior to or on index, Yes):
    N   PCT
0  25  49.0

Loop diuretic:
                         WINDOW   N   PCT
0  30 days prior to or on index  12  23.5
1  60 days prior to or on index  15  29.4
2  90 days prior to or on index  17  33.3

### Check age breakdown

In [132]:
def get_age_distribution(cohort_df, cohort_label="Cohort"):
    age_df = (
        cohort_df
        .join(patient_tbl.select("PATIENT_ID", "YEAR_OF_BIRTH"), on="PATIENT_ID", how="left")
        .with_column(
            "AGE",
            when(col("YEAR_OF_BIRTH").is_not_null(),
                 (col("INDEX_DATE").cast("date").substr(1, 4).cast("int") - col("YEAR_OF_BIRTH")))
            .otherwise(lit(None))
        )
        .with_column(
            "AGE_BIN",
            when(col("AGE").is_null(), lit("Missing"))
            .when(col("AGE") < 70, lit("<70"))
            .when(col("AGE") < 80, lit("70-79"))
            .when(col("AGE") < 90, lit("80-89"))
            .otherwise(lit("90+"))
        )
    )

    print("Joined")

    dist = (
        age_df.group_by("AGE_BIN")
        .agg(count_distinct("PATIENT_ID").alias("N"))
        .to_pandas()
    )

    print("dist")

    total_n = dist["N"].sum()
    dist["PCT"] = (100 * dist["N"] / total_n).round(1)

    print(f"\n=== {cohort_label} (N={total_n}) ===")
    print(dist.sort_values("N", ascending=False))

    return dist

In [133]:
get_age_distribution(step7_aco_att_df, "Acoramidis")

Joined
dist

=== Acoramidis (N=51) ===
   AGE_BIN   N   PCT
3    80-89  28  54.9
1    70-79  14  27.5
0      <70   5   9.8
2  Missing   4   7.8

   AGE_BIN   N   PCT
0      <70   5   9.8
1    70-79  14  27.5
2  Missing   4   7.8
3    80-89  28  54.9

In [134]:
get_age_distribution(step7_vut_att_df, "Vutrisiran")

Joined
dist

=== Vutrisiran (N=115) ===
   AGE_BIN   N   PCT
2    80-89  53  46.1
3    70-79  51  44.3
0      <70   7   6.1
4  Missing   3   2.6
1      90+   1   0.9

   AGE_BIN   N   PCT
0      <70   7   6.1
1      90+   1   0.9
2    80-89  53  46.1
3    70-79  51  44.3
4  Missing   3   2.6

In [139]:
def get_patient_level_egfr(cohort_df, cohort_label="Cohort", window_months=6):
    """
    Returns patient-level eGFR values for manual inspection.
    """
    print(cohort_label)
    total_n = cohort_df.select("PATIENT_ID").distinct().count()

    index_dates = cohort_df.select("PATIENT_ID", "INDEX_DATE").to_pandas()
    index_dates["INDEX_DATE"] = pd.to_datetime(index_dates["INDEX_DATE"])

    print("check1")
    egfr_raw = (
        cohort_df
        .join(lab_tbl.filter(col("CODE").isin(egfr_codes)).filter(col("LAB_RESULT_NUM_VAL").is_not_null()),
              on="PATIENT_ID")
        .filter(col("DATE") <= col("INDEX_DATE"))
        .select("PATIENT_ID", "DATE", col("LAB_RESULT_NUM_VAL").alias("EGFR_VAL"))
        .to_pandas()
    )
    egfr_raw["DATE"] = pd.to_datetime(egfr_raw["DATE"])
    print("check2")
    
    merged = egfr_raw.merge(index_dates, on="PATIENT_ID")
    merged["MONTHS_DIFF"] = (merged["INDEX_DATE"] - merged["DATE"]).dt.days / 30.44
    merged = merged[merged["MONTHS_DIFF"] <= window_months]

    latest = merged.sort_values("DATE").groupby("PATIENT_ID").tail(1)[["PATIENT_ID", "DATE", "EGFR_VAL"]]
    print("check3")

    combined = index_dates[["PATIENT_ID", "INDEX_DATE"]].merge(latest, on="PATIENT_ID", how="left")
    combined["COHORT"] = cohort_label
    combined["EGFR_CAT"] = pd.cut(combined["EGFR_VAL"], bins=[-float("inf"), 45, float("inf")], labels=["<45", "≥45"])

    print(f"\n=== {cohort_label} (N={total_n}) — eGFR within {window_months}mo ===")
    print(combined["EGFR_VAL"].describe())

    return combined

In [140]:
# Pull both cohorts
aco_egfr = get_patient_level_egfr(step7_aco_att_df, cohort_label="Acoramidis", window_months=6)
vut_egfr = get_patient_level_egfr(step7_vut_att_df, cohort_label="Vutrisiran", window_months=6)

all_egfr = pd.concat([aco_egfr, vut_egfr], ignore_index=True)

Acoramidis
check1
check2
check3

=== Acoramidis (N=51) — eGFR within 6mo ===
count    39.000000
mean     58.000000
std      22.372445
min      14.000000
25%      44.000000
50%      56.000000
75%      74.500000
max      99.000000
Name: EGFR_VAL, dtype: float64
Vutrisiran
check1
check2
check3

=== Vutrisiran (N=115) — eGFR within 6mo ===
count      86.000000
mean      292.988372
std      1039.269727
min        16.000000
25%        42.000000
50%        55.500000
75%        70.000000
max      6497.000000
Name: EGFR_VAL, dtype: float64

In [141]:

# Summary stats side by side
print("\neGFR summary by cohort:")
print(all_egfr.groupby("COHORT")["EGFR_VAL"].describe())

# Category counts (cross-check against your table)
print("\neGFR category counts by cohort:")
print(all_egfr.groupby(["COHORT", "EGFR_CAT"], dropna=False)["PATIENT_ID"].nunique())

eGFR summary by cohort:
            count        mean          std   min   25%   50%   75%     max
COHORT
Acoramidis   39.0   58.000000    22.372445  14.0  44.0  56.0  74.5    99.0
Vutrisiran   86.0  292.988372  1039.269727  16.0  42.0  55.5  70.0  6497.0

eGFR category counts by cohort:
COHORT      EGFR_CAT
Acoramidis  <45         11
            ≥45         28
            nan         12
Vutrisiran  <45         28
            ≥45         58
            nan         29
Name: PATIENT_ID, dtype: int64

/tmp/ipykernel_1642/116323806.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(all_egfr.groupby(["COHORT", "EGFR_CAT"], dropna=False)["PATIENT_ID"].nunique())

In [142]:
outliers = all_egfr[all_egfr["EGFR_VAL"] > 200].sort_values("EGFR_VAL", ascending=False)
print(outliers[["PATIENT_ID", "COHORT", "DATE", "EGFR_VAL"]])

    PATIENT_ID      COHORT       DATE  EGFR_VAL
112       eQHC  Vutrisiran 2025-07-02    6497.0
133       WQXD  Vutrisiran 2025-06-18    5183.0
70        WgQC  Vutrisiran 2025-05-31    4088.0
55        WwsC  Vutrisiran 2025-07-04    2993.0
65         WQ6  Vutrisiran 2025-06-20    2044.0

In [143]:
outlier_ids = outliers["PATIENT_ID"].tolist()

session.table("DATA_202511.LAB_RESULT") \
    .filter(col("PATIENT_ID").isin(outlier_ids)) \
    .filter(col("CODE").isin(egfr_codes)) \
    .filter(col("LAB_RESULT_NUM_VAL") > 200) \
    .select("PATIENT_ID", "CODE", "LAB_RESULT_NUM_VAL", "UNITS_OF_MEASURE", "DATE") \
    .show(20)

-----------------------------------------------------------------------------------
|"PATIENT_ID"  |"CODE"   |"LAB_RESULT_NUM_VAL"  |"UNITS_OF_MEASURE"  |"DATE"      |
-----------------------------------------------------------------------------------
|WwsC          |98979-8  |2774                  |mL/min/{1.73_m2}    |2025-09-13  |
|WQ6           |98979-8  |2847                  |mL/min/{1.73_m2}    |2025-06-27  |
|WwsC          |98979-8  |3650                  |mL/min/{1.73_m2}    |2023-05-09  |
|WwsC          |98979-8  |3869                  |mL/min/{1.73_m2}    |2023-03-11  |
|eQHC          |98979-8  |6424                  |mL/min/{1.73_m2}    |2025-01-30  |
|WwsC          |98979-8  |3723                  |mL/min/{1.73_m2}    |2025-04-10  |
|WwsC          |98979-8  |3066                  |mL/min/{1.73_m2}    |2024-06-15  |
|WQ6           |98979-8  |2993                  |mL/min/{1.73_m2}    |2024-09-11  |
|WwsC          |98979-8  |3796                  |mL/min/{1.73_m2}    |2024-11-19  |
|WQ6           |98979-8  |3212                  |mL/min/{1.73_m2}    |2024-09-04  |
|WQXD          |98979-8  |5183                  |mL/min/{1.73_m2}    |2025-06-18  |
|WQ6           |98979-8  |2628                  |mL/min/{1.73_m2}    |2025-06-03  |
|WQ6           |98979-8  |3723                  |mL/min/{1.73_m2}    |2024-04-05  |
|WgQC          |98979-8  |4672                  |mL/min/{1.73_m2}    |2023-11-22  |
|WwsC          |98979-8  |2993                  |mL/min/{1.73_m2}    |2025-05-07  |
|WQ6           |98979-8  |3066                  |mL/min/{1.73_m2}    |2024-11-15  |
|WgQC          |98979-8  |4307                  |mL/min/{1.73_m2}    |2023-03-02  |
|WwsC          |98979-8  |3577                  |mL/min/{1.73_m2}    |2023-04-11  |
|WQ6           |98979-8  |3650                  |mL/min/{1.73_m2}    |2024-05-02  |
|WwsC          |98979-8  |3650                  |mL/min/{1.73_m2}    |2023-10-04  |
-----------------------------------------------------------------------------------

In [144]:
all_egfr_clean = all_egfr[all_egfr["EGFR_VAL"].between(0, 200) | all_egfr["EGFR_VAL"].isna()]

print("eGFR summary by cohort (outliers removed):")
print(all_egfr_clean.groupby("COHORT")["EGFR_VAL"].describe())

print("\neGFR category counts by cohort (outliers removed):")
print(all_egfr_clean.groupby(["COHORT", "EGFR_CAT"], dropna=False)["PATIENT_ID"].nunique())

eGFR summary by cohort (outliers removed):
            count       mean        std   min   25%   50%   75%    max
COHORT
Acoramidis   39.0  58.000000  22.372445  14.0  44.0  56.0  74.5   99.0
Vutrisiran   81.0  54.222222  19.036150  16.0  41.0  55.0  66.0  111.0

eGFR category counts by cohort (outliers removed):
COHORT      EGFR_CAT
Acoramidis  <45         11
            ≥45         28
            nan         12
Vutrisiran  <45         28
            ≥45         53
            nan         29
Name: PATIENT_ID, dtype: int64

/tmp/ipykernel_1642/1314508182.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(all_egfr_clean.groupby(["COHORT", "EGFR_CAT"], dropna=False)["PATIENT_ID"].nunique())